# -*- coding = utf-8 -*-
# @Time: 2025/10/25 下午2:28
# @Author: 柯影数智
# @File: smoke_maps_en.py
# @Email: 1090461393@qq.com
# @SoftWare: PyCharm

# -*- coding: utf-8 -*-
# scripts/smoke_maps_en.py
# English map tests (Basemap / Choropleth / Points / Raster overlays)
from __future__ import annotations

import os
import sys
import random
from pathlib import Path
from typing import List, Optional, Tuple

from src.main import ResearchDrawApp

# ---------- Paths ----------
THIS_FILE = Path(__file__).resolve()
PROJECT_ROOT = THIS_FILE.parent.parent.resolve()
# Prefer env MAP_BASEMAP_ROOT; otherwise <repo>/data/geo
BASEMAP_ROOT = Path(os.environ.get("MAP_BASEMAP_ROOT") or (PROJECT_ROOT / "data" / "geo")).resolve()

# Test data dir (auto-created)
DATA_DIR = (PROJECT_ROOT / "data" / "test").resolve()
DATA_DIR.mkdir(parents=True, exist_ok=True)

# Input test data (autogenerated if missing)
POINTS_CSV = (DATA_DIR / "points_en.csv").resolve()
WORLD_CHORO_CSV = (DATA_DIR / "world_values_en.csv").resolve()      # columns: ISO_A3,value
CHINA_CHORO_CSV = (DATA_DIR / "china_l1_values_en.csv").resolve()   # columns: NAME_1,value

# Demo rasters (prefer <repo>/data/*.tif; fallback to BASEMAP_ROOT)
RASTER_TIF_WORLD_PRIMARY = (PROJECT_ROOT / "data" / "demo_world.tif").resolve()
RASTER_TIF_WORLD_FALLBACK = (BASEMAP_ROOT / "demo_world.tif").resolve()
RASTER_TIF_CHINA_PRIMARY = (PROJECT_ROOT / "data" / "demo_china.tif").resolve()
RASTER_TIF_CHINA_FALLBACK = (BASEMAP_ROOT / "demo_china.tif").resolve()

MAP_THEME = "journal"
NO_SHOW = True
RNG_SEED = 20251025
random.seed(RNG_SEED)


# ---------- Helpers ----------
def fail(msg: str):
    print(f"[ERROR] {msg}")
    sys.exit(1)


def ensure_basemap_dir():
    if not BASEMAP_ROOT.exists():
        fail(
            "Offline basemap root not found: "
            f"{BASEMAP_ROOT}\nPlease set MAP_BASEMAP_ROOT or put data under <repo>/data/geo"
        )


def find_ne_admin0_path(root: Path) -> Optional[Path]:
    """Find Natural Earth admin0 (countries) file."""
    d = (root / "world" / "natural_earth" / "admin0")
    if not d.exists():
        return None
    # Typical prefixes: ne_10m_admin_0*
    for ext in (".gpkg", ".geojson", ".json", ".shp"):
        for p in d.glob(f"ne_10m_admin_0*{ext}"):
            return p
    # Fallback: any shp
    for p in d.glob("*.shp"):
        return p
    return None


def find_gadm_l1_path(root: Path) -> Optional[Path]:
    """Find GADM China level 1 (provinces) data."""
    gpkg = root / "china" / "gadm" / "gpkg" / "gadm41_CHN.gpkg"
    if gpkg.exists():
        return gpkg
    shp_dir = root / "china" / "gadm" / "shp"
    for p in shp_dir.glob("gadm41_CHN_1*.shp"):
        return p
    return None


def make_world_values_csv(out_csv: Path):
    """Build a world choropleth CSV from NE admin0 with random values."""
    import geopandas as gpd
    import pandas as pd

    p = find_ne_admin0_path(BASEMAP_ROOT)
    if p is None:
        fail(f"NE admin0 not found under {BASEMAP_ROOT}/world/natural_earth/admin0")
    g = gpd.read_file(p)
    key = None
    for k in ["ISO_A3", "iso_a3", "ADM0_A3"]:
        if k in g.columns:
            key = k
            break
    if key is None:
        fail(f"admin0 missing ISO_A3/ADM0_A3; sample cols: {list(g.columns)[:15]}")

    vals = [round(random.random() * 100, 2) for _ in range(len(g))]
    df = pd.DataFrame({"ISO_A3": g[key], "value": vals})
    df.to_csv(out_csv, index=False, encoding="utf-8")
    print(f"[OK] Generated world choropleth CSV: {out_csv}")


def make_china_l1_values_csv(out_csv: Path):
    """Build a China L1 choropleth CSV (NAME_1,value) from GADM."""
    import geopandas as gpd
    import pandas as pd
    import numpy as np

    p = find_gadm_l1_path(BASEMAP_ROOT)
    if p is None:
        fail(f"GADM China L1 not found under {BASEMAP_ROOT}/china/gadm/gpkg or .../shp")
    if p.suffix.lower() == ".gpkg":
        g = gpd.read_file(p, layer="gadm41_CHN_1")
    else:
        g = gpd.read_file(p)
    if "NAME_1" not in g.columns:
        fail(f"GADM L1 missing NAME_1; sample cols: {list(g.columns)[:15]}")
    rng = np.random.default_rng(RNG_SEED)
    df = pd.DataFrame({"NAME_1": g["NAME_1"], "value": np.round(rng.random(len(g)) * 100, 2)})
    df.to_csv(out_csv, index=False, encoding="utf-8")
    print(f"[OK] Generated China L1 choropleth CSV: {out_csv}")


def make_points_csv(out_csv: Path):
    """Generate global scatter points with name/group/size."""
    import pandas as pd
    import numpy as np

    rng = np.random.default_rng(RNG_SEED)
    n = 80
    lon = rng.uniform(-160, 160, n)
    lat = rng.uniform(-60, 75, n)
    size = np.round(rng.normal(50, 20, n).clip(5, 120), 1)
    group = rng.choice(["Group A", "Group B", "Group C"], size=n, p=[0.35, 0.35, 0.30])
    name = [f"Site {i + 1}" for i in range(n)]
    pd.DataFrame({"lon": lon, "lat": lat, "size": size, "group": group, "name": name}).to_csv(
        out_csv, index=False
    )
    print(f"[OK] Generated points CSV: {out_csv}")


def ensure_demo_data():
    ensure_basemap_dir()
    if not WORLD_CHORO_CSV.exists():
        make_world_values_csv(WORLD_CHORO_CSV)
    if not CHINA_CHORO_CSV.exists():
        make_china_l1_values_csv(CHINA_CHORO_CSV)
    if not POINTS_CSV.exists():
        make_points_csv(POINTS_CSV)


def run(argv_list: List[str]) -> None:
    """Print the command-like args and run the CLI entry."""
    args = [str(a) for a in argv_list if a]
    printable = " ".join(args)
    print(f">>> running: {printable}")
    ResearchDrawApp(args).run()


def ensure_exists(p: Path, desc: str) -> bool:
    if p.exists():
        return True
    print(f"[SKIP] Missing {desc}: {p}")
    return False


def pick_first_existing(paths: List[Path]) -> Optional[Path]:
    for p in paths:
        if p and p.exists():
            return p
    return None


# ---------- Tests ----------
def test_world_admin0_base():
    run([
        "--plot", "world",
        "--map-theme", MAP_THEME,
        "--basemap-root", str(BASEMAP_ROOT),
        "--title", "World Countries (Admin0)",
        "--label-names",
        "--crs", "EPSG:4326",
        "--tight",
        "--no-show" if NO_SHOW else None,
    ])


def test_world_admin1_subset():
    # Let the library auto-detect the country name column (adm0_name/admin/name_en…)
    run([
        "--plot", "world_admin1",
        "--countries", "China,United States of America,India",
        "--label-names",
        "--map-theme", MAP_THEME,
        "--basemap-root", str(BASEMAP_ROOT),
        "--title", "World Admin1 (China/USA/India)",
        "--crs", "EPSG:4326",
        "--tight",
        "--no-show" if NO_SHOW else None,
    ])


def test_china_l1_label():
    run([
        "--plot", "china",
        "--level", "1",
        "--label-names",
        "--highlight", "北京市,上海市,广东省,四川省",  # keep native names for matching
        "--map-theme", MAP_THEME,
        "--basemap-root", str(BASEMAP_ROOT),
        "--title", "China Provinces (L1) with Labels",
        "--crs", "EPSG:4326",
        "--tight",
        "--no-show" if NO_SHOW else None,
    ])


def test_choropleth_world():
    if not ensure_exists(WORLD_CHORO_CSV, "world choropleth CSV (ISO_A3,value)"):
        return
    run([
        "--plot", "choropleth_world",
        "--mode", "file",
        "--file", str(WORLD_CHORO_CSV),
        "--key-col", "ISO_A3",
        "--value-col", "value",
        "--on", "iso_a3",
        "--scheme", "natural",
        "--k", "6",
        "--cmap", MAP_THEME,
        "--map-theme", MAP_THEME,
        "--basemap-root", str(BASEMAP_ROOT),
        "--title", "World Choropleth (Natural Breaks)",
        "--crs", "EPSG:4326",
        "--tight",
        "--no-show" if NO_SHOW else None,
    ])


def test_choropleth_china_l1():
    if not ensure_exists(CHINA_CHORO_CSV, "China L1 choropleth CSV (NAME_1,value)"):
        return
    run([
        "--plot", "choropleth_china",
        "--mode", "file",
        "--file", str(CHINA_CHORO_CSV),
        "--level", "1",
        "--key-col", "NAME_1",
        "--value-col", "value",
        "--on", "NAME",
        "--scheme", "quantiles",
        "--k", "5",
        "--cmap", "Reds",
        "--map-theme", MAP_THEME,
        "--basemap-root", str(BASEMAP_ROOT),
        "--title", "China Choropleth (Quintiles, L1)",
        "--crs", "EPSG:4326",
        "--tight",
        "--no-show" if NO_SHOW else None,
    ])


def test_raster_overlay_world():
    raster = pick_first_existing([RASTER_TIF_WORLD_PRIMARY, RASTER_TIF_WORLD_FALLBACK])
    if raster is None:
        print(f"[SKIP] Missing demo world raster: {RASTER_TIF_WORLD_PRIMARY} or {RASTER_TIF_WORLD_FALLBACK}")
        return
    run([
        "--plot", "raster",
        "--raster-file", str(raster),
        "--basemap", "world_admin0",
        "--alpha", "0.60",
        "--map-theme", MAP_THEME,
        "--basemap-root", str(BASEMAP_ROOT),
        "--title", "World Basemap + Raster Overlay",
        "--crs", "EPSG:4326",
        "--tight",
        "--no-show" if NO_SHOW else None,
    ])


def test_raster_overlay_china():
    raster = pick_first_existing([RASTER_TIF_CHINA_PRIMARY, RASTER_TIF_CHINA_FALLBACK])
    if raster is None:
        print(f"[SKIP] Missing demo China raster: {RASTER_TIF_CHINA_PRIMARY} or {RASTER_TIF_CHINA_FALLBACK}")
        return
    run([
        "--plot", "raster",
        "--raster-file", str(raster),
        "--basemap", "china_l1",
        "--alpha", "0.60",
        "--map-theme", MAP_THEME,
        "--basemap-root", str(BASEMAP_ROOT),
        "--title", "China L1 Basemap + Raster Overlay",
        "--crs", "EPSG:4326",
        "--tight",
        "--no-show" if NO_SHOW else None,
    ])


def test_points_overlay_world():
    if not ensure_exists(POINTS_CSV, "points CSV (lon,lat,name,group,size)"):
        return
    run([
        "--plot", "points",
        "--mode", "file",
        "--file", str(POINTS_CSV),
        "--lon-col", "lon",
        "--lat-col", "lat",
        "--label-col", "name",
        "--size-col", "size",
        "--hue-col", "group",
        "--basemap", "world_admin0",
        "--size-range", "24,180",
        "--map-theme", MAP_THEME,
        "--basemap-root", str(BASEMAP_ROOT),
        "--title", "Global Research Sites (Categorical Color + Proportional Symbols)",
        "--crs", "EPSG:4326",
        "--tight",
        "--no-show" if NO_SHOW else None,
    ])


# ---------- Main ----------
if __name__ == "__main__":
    print(f"PROJECT_ROOT : {PROJECT_ROOT}")
    print(f"BASEMAP_ROOT : {BASEMAP_ROOT}")
    print(f"DATA_DIR     : {DATA_DIR}")
    print("Starting English map tests...")
    ensure_demo_data()

    # A. Basemap fundamentals
    test_world_admin0_base()
    test_world_admin1_subset()
    test_china_l1_label()

    # B. Choropleths
    test_choropleth_world()
    test_choropleth_china_l1()

    # C. Rasters & Points
    test_raster_overlay_world()
    test_raster_overlay_china()
    test_points_overlay_world()

    print("✅ All English map tests completed.")
